name: CI - Compile

on:
  push:
    branches: [master, develop]

jobs:
  build-yocto:
    runs-on: [self-hosted, linux, x64, yocto]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Yocto Rootfs
        run: |
          ./balena-yocto-scripts/build/barys -m rockpi-px30

      - name: Compress the output images
        run: |
          tar -czvf images.tar.gz -C ./tmp/deploy/images/rockpi-px30 .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: images
          path: images.tar.gz
          retention-days: 1
